/**
 * Self-hosts the three type families of §9b.
 *
 * §9f requires the exported static page to render with the network disabled —
 * no CDN fonts. That rules out linking Google Fonts at runtime, so the woff2
 * files are downloaded once into public/fonts/ and committed. This script also
 * emits `inline.css`, the same faces as base64 data URIs, which the client
 * fetches at export time and embeds in the standalone page.
 *
 * Run: npx tsx scripts/fetch-fonts.ts
 */
import { readFile, writeFile, mkdir } from "node:fs/promises";
import { existsSync } from "node:fs";
import { join } from "node:path";

const OUT_DIR = join(process.cwd(), "public", "fonts");

const GOOGLE_CSS =
  "https://fonts.googleapis.com/css2?" +
  "family=Archivo:wdth,wght@62..125,400..700&" +
  "family=Public+Sans:wght@400..600&" +
  "family=IBM+Plex+Mono:wght@400;500&display=swap";

const UA =
  "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 " +
  "(KHTML, like Gecko) Chrome/120.0 Safari/537.36";

/** Only latin and latin-ext; the rest triples the payload for no benefit here. */
const KEEP_SUBSETS = new Set(["latin", "latin-ext"]);

type Face = { subset: string; block: string; url: string; family: string; weight: string };

async function main() {
  await mkdir(OUT_DIR, { recursive: true });

  const cssPath = join(OUT_DIR, "gf.css");
  let css: string;
  if (existsSync(cssPath)) {
    css = await readFile(cssPath, "utf8");
  } else {
    css = await (await fetch(GOOGLE_CSS, { headers: { "User-Agent": UA } })).text();
    await writeFile(cssPath, css);
  }

  const faces = parseFaces(css).filter((f) => KEEP_SUBSETS.has(f.subset));
  const localBlocks: string[] = [];
  const inlineBlocks: string[] = [];

  for (const face of faces) {
    const slug = `${face.family.replace(/\s+/g, "-")}-${face.weight.replace(/\s+/g, "")}-${face.subset}`
      .replace(/[^a-zA-Z0-9.-]/g, "_")
      .toLowerCase();
    const filename = `${slug}.woff2`;
    const dest = join(OUT_DIR, filename);
    if (!existsSync(dest)) {
      const buf = Buffer.from(await (await fetch(face.url)).arrayBuffer());
      await writeFile(dest, buf);
      console.log(`downloaded ${filename} (${(buf.length / 1024).toFixed(1)} KB)`);
    }
    const bytes = await readFile(dest);
    localBlocks.push(face.block.replace(/url\([^)]+\)/, `url("/fonts/${filename}")`));
    inlineBlocks.push(
      face.block.replace(
        /url\([^)]+\)/,
        `url("data:font/woff2;base64,${bytes.toString("base64")}")`,
      ),
    );
  }

  const header =
    "/* Generated by scripts/fetch-fonts.ts — do not edit. Fonts are SIL Open Font License 1.1. */\n";
  await writeFile(join(OUT_DIR, "fonts.css"), header + localBlocks.join("\n") + "\n");
  await writeFile(join(OUT_DIR, "inline.css"), header + inlineBlocks.join("\n") + "\n");
  console.log(`wrote ${faces.length} faces to public/fonts/{fonts,inline}.css`);
}

function parseFaces(css: string): Face[] {
  const out: Face[] = [];
  // Google's CSS emits `/* subset */` immediately before each @font-face block.
  const re = /\/\*\s*([a-z-]+)\s*\*\/\s*(@font-face\s*\{[^}]*\})/g;
  let m: RegExpExecArray | null;
  while ((m = re.exec(css)) !== null) {
    const block = m[2];
    const url = block.match(/url\(([^)]+)\)/)?.[1] ?? "";
    out.push({
      subset: m[1],
      block,
      url: url.replace(/['"]/g, ""),
      family: block.match(/font-family:\s*['"]([^'"]+)['"]/)?.[1] ?? "unknown",
      weight: block.match(/font-weight:\s*([^;]+);/)?.[1]?.trim() ?? "400",
    });
  }
  return out;
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
